package com.envmgr.labelservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * You have reached the Help page for the Label Server Web Service.
 *
 * This class was generated by Apache CXF 3.2.7
 * 2019-10-28T17:05:01.001-03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "EwsLabelService",
                  wsdlLocation = "file:/Users/mymac/slingr/endpoints/endicia-endpoint/src/main/resources/wsdl/EwsLabelService.wsdl",
                  targetNamespace = "www.envmgr.com/LabelService")
public class EwsLabelService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("www.envmgr.com/LabelService", "EwsLabelService");
    public final static QName EwsLabelServiceSoap12 = new QName("www.envmgr.com/LabelService", "EwsLabelServiceSoap12");
    public final static QName EwsLabelServiceSoap = new QName("www.envmgr.com/LabelService", "EwsLabelServiceSoap");
    public final static QName EwsLabelServiceHttpGet = new QName("www.envmgr.com/LabelService", "EwsLabelServiceHttpGet");
    public final static QName EwsLabelServiceHttpPost = new QName("www.envmgr.com/LabelService", "EwsLabelServiceHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/mymac/slingr/endpoints/endicia-endpoint/src/main/resources/wsdl/EwsLabelService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EwsLabelService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/mymac/slingr/endpoints/endicia-endpoint/src/main/resources/wsdl/EwsLabelService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EwsLabelService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EwsLabelService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EwsLabelService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EwsLabelService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EwsLabelService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EwsLabelService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EwsLabelServiceSoap
     */
    @WebEndpoint(name = "EwsLabelServiceSoap12")
    public EwsLabelServiceSoap getEwsLabelServiceSoap12() {
        return super.getPort(EwsLabelServiceSoap12, EwsLabelServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EwsLabelServiceSoap
     */
    @WebEndpoint(name = "EwsLabelServiceSoap12")
    public EwsLabelServiceSoap getEwsLabelServiceSoap12(WebServiceFeature... features) {
        return super.getPort(EwsLabelServiceSoap12, EwsLabelServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns EwsLabelServiceSoap
     */
    @WebEndpoint(name = "EwsLabelServiceSoap")
    public EwsLabelServiceSoap getEwsLabelServiceSoap() {
        return super.getPort(EwsLabelServiceSoap, EwsLabelServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EwsLabelServiceSoap
     */
    @WebEndpoint(name = "EwsLabelServiceSoap")
    public EwsLabelServiceSoap getEwsLabelServiceSoap(WebServiceFeature... features) {
        return super.getPort(EwsLabelServiceSoap, EwsLabelServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns EwsLabelServiceHttpGet
     */
    @WebEndpoint(name = "EwsLabelServiceHttpGet")
    public EwsLabelServiceHttpGet getEwsLabelServiceHttpGet() {
        return super.getPort(EwsLabelServiceHttpGet, EwsLabelServiceHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EwsLabelServiceHttpGet
     */
    @WebEndpoint(name = "EwsLabelServiceHttpGet")
    public EwsLabelServiceHttpGet getEwsLabelServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(EwsLabelServiceHttpGet, EwsLabelServiceHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns EwsLabelServiceHttpPost
     */
    @WebEndpoint(name = "EwsLabelServiceHttpPost")
    public EwsLabelServiceHttpPost getEwsLabelServiceHttpPost() {
        return super.getPort(EwsLabelServiceHttpPost, EwsLabelServiceHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EwsLabelServiceHttpPost
     */
    @WebEndpoint(name = "EwsLabelServiceHttpPost")
    public EwsLabelServiceHttpPost getEwsLabelServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(EwsLabelServiceHttpPost, EwsLabelServiceHttpPost.class, features);
    }

}
