package com.envmgr.labelservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2021-09-07T18:10:46.737-03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "www.envmgr.com/LabelService", name = "EwsLabelServiceSoap")
@XmlSeeAlso({core.labelnumberservice.ObjectFactory.class, ObjectFactory.class})
public interface EwsLabelServiceSoap {

    @WebMethod(operationName = "GetPackagePickupList", action = "www.envmgr.com/LabelService/GetPackagePickupList")
    @RequestWrapper(localName = "GetPackagePickupList", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupList")
    @ResponseWrapper(localName = "GetPackagePickupListResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupListResponse")
    @WebResult(name = "PackagePickupListResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupListResponse getPackagePickupList(
        @WebParam(name = "PackagePickupListRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PackagePickupListRequest packagePickupListRequest
    );

    @WebMethod(operationName = "CalculateDdpRate", action = "www.envmgr.com/LabelService/CalculateDdpRate")
    @RequestWrapper(localName = "CalculateDdpRate", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculateDdpRate")
    @ResponseWrapper(localName = "CalculateDdpRateResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculateDdpRateResponse")
    @WebResult(name = "DdpRateResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DdpRateResponse calculateDdpRate(
        @WebParam(name = "DdpRateRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.DdpRateRequest ddpRateRequest
    );

    @WebMethod(operationName = "CreateNotificationSettingRequestXML", action = "www.envmgr.com/LabelService/CreateNotificationSettingRequestXML")
    @RequestWrapper(localName = "CreateNotificationSettingRequestXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateNotificationSettingRequestXML")
    @ResponseWrapper(localName = "CreateNotificationSettingRequestXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateNotificationSettingRequestXMLResponse")
    @WebResult(name = "GetNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.CreateNotificationSettingResult createNotificationSettingRequestXML(
        @WebParam(name = "CreateNotificationSettingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String createNotificationSettingRequestXML
    );

    @WebMethod(operationName = "GetExtraServiceRates", action = "www.envmgr.com/LabelService/GetExtraServiceRates")
    @RequestWrapper(localName = "GetExtraServiceRates", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetExtraServiceRates")
    @ResponseWrapper(localName = "GetExtraServiceRatesResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetExtraServiceRatesResponse")
    @WebResult(name = "GetExtraServiceRatesResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetExtraServiceRateResponse getExtraServiceRates(
        @WebParam(name = "GetExtraServiceRatesRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.GetExtraServiceRatesRequest getExtraServiceRatesRequest
    );

    @WebMethod(operationName = "CreateBrandingXML", action = "www.envmgr.com/LabelService/CreateBrandingXML")
    @RequestWrapper(localName = "CreateBrandingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateBrandingXML")
    @ResponseWrapper(localName = "CreateBrandingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateBrandingXMLResponse")
    @WebResult(name = "GetBrandingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.CreateBrandingResult createBrandingXML(
        @WebParam(name = "CreateBrandingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String createBrandingRequestXML
    );

    @WebMethod(operationName = "StatusRequest", action = "www.envmgr.com/LabelService/StatusRequest")
    @RequestWrapper(localName = "StatusRequest", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.StatusRequest")
    @ResponseWrapper(localName = "StatusRequestResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.StatusRequestResponse")
    @WebResult(name = "PackageStatusResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackageStatusResponse statusRequest(
        @WebParam(name = "PackageStatusRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PackageStatusRequest packageStatusRequest
    );

    @WebMethod(operationName = "GetRefundXML", action = "www.envmgr.com/LabelService/GetRefundXML")
    @RequestWrapper(localName = "GetRefundXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRefundXML")
    @ResponseWrapper(localName = "GetRefundXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRefundXMLResponse")
    @WebResult(name = "RefundResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.RefundResponse getRefundXML(
        @WebParam(name = "RefundRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String refundRequestXML
    );

    @WebMethod(operationName = "GetPicNumberXml", action = "www.envmgr.com/LabelService/GetPicNumberXml")
    @RequestWrapper(localName = "GetPicNumberXml", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPicNumberXml")
    @ResponseWrapper(localName = "GetPicNumberXmlResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPicNumberXmlResponse")
    @WebResult(name = "LabelNumberResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.LabelNumberResponse getPicNumberXml(
        @WebParam(name = "PicNumberRequestXml", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String picNumberRequestXml
    );

    @WebMethod(operationName = "CloseAccount", action = "www.envmgr.com/LabelService/CloseAccount")
    @RequestWrapper(localName = "CloseAccount", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CloseAccount")
    @ResponseWrapper(localName = "CloseAccountResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CloseAccountResponse")
    @WebResult(name = "CloseAccountResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.SetPendingCloseAccountResponse closeAccount(
        @WebParam(name = "CloseAccountRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.CloseAccountRequest closeAccountRequest
    );

    @WebMethod(operationName = "UpdatePaymentInformation", action = "www.envmgr.com/LabelService/UpdatePaymentInformation")
    @RequestWrapper(localName = "UpdatePaymentInformation", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdatePaymentInformation")
    @ResponseWrapper(localName = "UpdatePaymentInformationResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdatePaymentInformationResponse")
    @WebResult(name = "UpdatePaymentInfoResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UpdatePaymentInfoResponse updatePaymentInformation(
        @WebParam(name = "UpdatePaymentInfoRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.UpdatePaymentInfoRequest updatePaymentInfoRequest
    );

    @WebMethod(operationName = "DeleteCarrier", action = "www.envmgr.com/LabelService/DeleteCarrier")
    @RequestWrapper(localName = "DeleteCarrier", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteCarrier")
    @ResponseWrapper(localName = "DeleteCarrierResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteCarrierResponse")
    @WebResult(name = "DeleteCarrierResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DeleteCarrierResponseComplex deleteCarrier(
        @WebParam(name = "DeleteCarrierRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.DeleteCarrierRequest deleteCarrierRequest
    );

    @WebMethod(operationName = "ChangePassPhrase", action = "www.envmgr.com/LabelService/ChangePassPhrase")
    @RequestWrapper(localName = "ChangePassPhrase", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ChangePassPhrase")
    @ResponseWrapper(localName = "ChangePassPhraseResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ChangePassPhraseResponse")
    @WebResult(name = "ChangePassPhraseRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ChangePassPhraseRequestResponse changePassPhrase(
        @WebParam(name = "ChangePassPhraseRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.ChangePassPhraseRequest changePassPhraseRequest
    );

    @WebMethod(operationName = "DeleteNotificationSettingXML", action = "www.envmgr.com/LabelService/DeleteNotificationSettingXML")
    @RequestWrapper(localName = "DeleteNotificationSettingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteNotificationSettingXML")
    @ResponseWrapper(localName = "DeleteNotificationSettingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteNotificationSettingXMLResponse")
    @WebResult(name = "DeleteNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DeleteNotificationSettingResult deleteNotificationSettingXML(
        @WebParam(name = "DeleteNotificationSettingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String deleteNotificationSettingRequestXML
    );

    @WebMethod(operationName = "GetPostageRateTableXML", action = "www.envmgr.com/LabelService/GetPostageRateTableXML")
    @RequestWrapper(localName = "GetPostageRateTableXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageRateTableXML")
    @ResponseWrapper(localName = "GetPostageRateTableXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageRateTableXMLResponse")
    @WebResult(name = "PostageRateResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PostageRateTableResponse getPostageRateTableXML(
        @WebParam(name = "PostageRateRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String postageRateRequestXML
    );

    @WebMethod(operationName = "ResetSuspendedAccount", action = "www.envmgr.com/LabelService/ResetSuspendedAccount")
    @RequestWrapper(localName = "ResetSuspendedAccount", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ResetSuspendedAccount")
    @ResponseWrapper(localName = "ResetSuspendedAccountResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ResetSuspendedAccountResponse")
    @WebResult(name = "ResetSuspendedAccountRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ResetSuspendedAccountRequestResponse resetSuspendedAccount(
        @WebParam(name = "ResetSuspendedAccountRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.ResetSuspendedAccountRequest resetSuspendedAccountRequest
    );

    @WebMethod(operationName = "CalculatePostageRateXML", action = "www.envmgr.com/LabelService/CalculatePostageRateXML")
    @RequestWrapper(localName = "CalculatePostageRateXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRateXML")
    @ResponseWrapper(localName = "CalculatePostageRateXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRateXMLResponse")
    @WebResult(name = "PostageRateResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PostageRateResponse calculatePostageRateXML(
        @WebParam(name = "PostageRateRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String postageRateRequestXML
    );

    @WebMethod(operationName = "CreateShipmentNotification", action = "www.envmgr.com/LabelService/CreateShipmentNotification")
    @RequestWrapper(localName = "CreateShipmentNotification", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateShipmentNotification")
    @ResponseWrapper(localName = "CreateShipmentNotificationResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateShipmentNotificationResponse")
    @WebResult(name = "GetShipmentNotificationResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.CreateShipmentNotificationResult createShipmentNotification(
        @WebParam(name = "CreateShipmentNotificationRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.CreateShipmentNotificationRequest createShipmentNotificationRequest
    );

    @WebMethod(operationName = "GetRetailAccountsXML", action = "www.envmgr.com/LabelService/GetRetailAccountsXML")
    @RequestWrapper(localName = "GetRetailAccountsXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRetailAccountsXML")
    @ResponseWrapper(localName = "GetRetailAccountsXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRetailAccountsXMLResponse")
    @WebResult(name = "RetailAccountsResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.RetailAccountsResponse getRetailAccountsXML(
        @WebParam(name = "RetailAccountsRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String retailAccountsRequestXML
    );

    @WebMethod(operationName = "GetVersion", action = "www.envmgr.com/LabelService/GetVersion")
    @RequestWrapper(localName = "GetVersion", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetVersion")
    @ResponseWrapper(localName = "GetVersionResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetVersionResponse")
    @WebResult(name = "GetVersionResults", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetVersionResults getVersion();

    @WebMethod(operationName = "GetUrlXML", action = "www.envmgr.com/LabelService/GetUrlXML")
    @RequestWrapper(localName = "GetUrlXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUrlXML")
    @ResponseWrapper(localName = "GetUrlXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUrlXMLResponse")
    @WebResult(name = "GetUrlResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetUrlResult getUrlXML(
        @WebParam(name = "GetUrlRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String getUrlRequestXML
    );

    @WebMethod(operationName = "CreateShipmentNotificationRequestXML", action = "www.envmgr.com/LabelService/CreateShipmentNotificationRequestXML")
    @RequestWrapper(localName = "CreateShipmentNotificationRequestXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateShipmentNotificationRequestXML")
    @ResponseWrapper(localName = "CreateShipmentNotificationRequestXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateShipmentNotificationRequestXMLResponse")
    @WebResult(name = "GetShipmentNotificationResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.CreateShipmentNotificationResult createShipmentNotificationRequestXML(
        @WebParam(name = "CreateShipmentNotificationRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String createShipmentNotificationRequestXML
    );

    @WebMethod(operationName = "ValidateAddress", action = "www.envmgr.com/LabelService/ValidateAddress")
    @RequestWrapper(localName = "ValidateAddress", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ValidateAddress")
    @ResponseWrapper(localName = "ValidateAddressResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ValidateAddressResponse")
    @WebResult(name = "ValidateAddressResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ValidateAddressInfoResponse validateAddress(
        @WebParam(name = "ValidateAddressRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.ValidateAddressInfoRequest validateAddressRequest
    );

    @WebMethod(operationName = "UpdateBrandingXML", action = "www.envmgr.com/LabelService/UpdateBrandingXML")
    @RequestWrapper(localName = "UpdateBrandingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateBrandingXML")
    @ResponseWrapper(localName = "UpdateBrandingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateBrandingXMLResponse")
    @WebResult(name = "UpdateBrandingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UpdateBrandingResult updateBrandingXML(
        @WebParam(name = "UpdateBrandingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String updateBrandingRequestXML
    );

    @WebMethod(operationName = "CreateDhlgmManifest", action = "www.envmgr.com/LabelService/CreateDhlgmManifest")
    @RequestWrapper(localName = "CreateDhlgmManifest", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateDhlgmManifest")
    @ResponseWrapper(localName = "CreateDhlgmManifestResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateDhlgmManifestResponse")
    @WebResult(name = "CreateDhlgmManifestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DhlgmManifestResponse createDhlgmManifest(
        @WebParam(name = "CreateDhlgmManifestRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.CreateDhlgmManifestRequest createDhlgmManifestRequest
    );

    @WebMethod(operationName = "GetBrandingXML", action = "www.envmgr.com/LabelService/GetBrandingXML")
    @RequestWrapper(localName = "GetBrandingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetBrandingXML")
    @ResponseWrapper(localName = "GetBrandingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetBrandingXMLResponse")
    @WebResult(name = "GetBrandingListResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetBrandingResult getBrandingXML(
        @WebParam(name = "GetBrandingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String getBrandingRequestXML
    );

    @WebMethod(operationName = "GetTransactionsListing", action = "www.envmgr.com/LabelService/GetTransactionsListing")
    @RequestWrapper(localName = "GetTransactionsListing", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetTransactionsListing")
    @ResponseWrapper(localName = "GetTransactionsListingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetTransactionsListingResponse")
    @WebResult(name = "TransactionsListingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.TransactionsListingResponse getTransactionsListing(
        @WebParam(name = "GetTransactionsListingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.GetTransactionsListingRequest getTransactionsListingRequest
    );

    @WebMethod(operationName = "CloseAccountXML", action = "www.envmgr.com/LabelService/CloseAccountXML")
    @RequestWrapper(localName = "CloseAccountXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CloseAccountXML")
    @ResponseWrapper(localName = "CloseAccountXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CloseAccountXMLResponse")
    @WebResult(name = "CloseAccountResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.SetPendingCloseAccountResponse closeAccountXML(
        @WebParam(name = "CloseAccountRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String closeAccountRequestXML
    );

    @WebMethod(operationName = "GetAccountStatusXML", action = "www.envmgr.com/LabelService/GetAccountStatusXML")
    @RequestWrapper(localName = "GetAccountStatusXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetAccountStatusXML")
    @ResponseWrapper(localName = "GetAccountStatusXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetAccountStatusXMLResponse")
    @WebResult(name = "AccountStatusResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.AccountStatusResponse getAccountStatusXML(
        @WebParam(name = "AccountStatusRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String accountStatusRequestXML
    );

    @WebMethod(operationName = "VoideVSLabelXML", action = "www.envmgr.com/LabelService/VoideVSLabelXML")
    @RequestWrapper(localName = "VoideVSLabelXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.VoideVSLabelXML")
    @ResponseWrapper(localName = "VoideVSLabelXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.VoideVSLabelXMLResponse")
    @WebResult(name = "VoidLabelResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.VoidLabelResponse voideVSLabelXML(
        @WebParam(name = "VoidLabelRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String voidLabelRequestXML
    );

    @WebMethod(operationName = "GetChallengeQuestion", action = "www.envmgr.com/LabelService/GetChallengeQuestion")
    @RequestWrapper(localName = "GetChallengeQuestion", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetChallengeQuestion")
    @ResponseWrapper(localName = "GetChallengeQuestionResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetChallengeQuestionResponse")
    @WebResult(name = "ChallengeQuestionResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ChallengeQuestionResponse getChallengeQuestion(
        @WebParam(name = "ChallengeQuestionRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.ChallengeQuestionRequest challengeQuestionRequest
    );

    @WebMethod(operationName = "GetPackagePickupCancelXML", action = "www.envmgr.com/LabelService/GetPackagePickupCancelXML")
    @RequestWrapper(localName = "GetPackagePickupCancelXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupCancelXML")
    @ResponseWrapper(localName = "GetPackagePickupCancelXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupCancelXMLResponse")
    @WebResult(name = "PackagePickupCancelResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupCancelResponse getPackagePickupCancelXML(
        @WebParam(name = "PackagePickupCancelRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String packagePickupCancelRequestXML
    );

    @WebMethod(operationName = "CreateNotificationSetting", action = "www.envmgr.com/LabelService/CreateNotificationSetting")
    @RequestWrapper(localName = "CreateNotificationSetting", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateNotificationSetting")
    @ResponseWrapper(localName = "CreateNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateNotificationSettingResponse")
    @WebResult(name = "GetNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.CreateNotificationSettingResult createNotificationSetting(
        @WebParam(name = "CreateNotificationSettingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.CreateNotificationSettingRequest createNotificationSettingRequest
    );

    @WebMethod(operationName = "DeleteNotificationSetting", action = "www.envmgr.com/LabelService/DeleteNotificationSetting")
    @RequestWrapper(localName = "DeleteNotificationSetting", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteNotificationSetting")
    @ResponseWrapper(localName = "DeleteNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteNotificationSettingResponse")
    @WebResult(name = "DeleteNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DeleteNotificationSettingResult deleteNotificationSetting(
        @WebParam(name = "DeleteNotificationSettingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.DeleteNotificationSettingRequest deleteNotificationSettingRequest
    );

    @WebMethod(operationName = "GetSCANXML", action = "www.envmgr.com/LabelService/GetSCANXML")
    @RequestWrapper(localName = "GetSCANXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetSCANXML")
    @ResponseWrapper(localName = "GetSCANXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetSCANXMLResponse")
    @WebResult(name = "SCANResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.SCANResponse getSCANXML(
        @WebParam(name = "GetSCANRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String getSCANRequestXML
    );

    @WebMethod(operationName = "GetPackagePickupAvailabilityXML", action = "www.envmgr.com/LabelService/GetPackagePickupAvailabilityXML")
    @RequestWrapper(localName = "GetPackagePickupAvailabilityXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupAvailabilityXML")
    @ResponseWrapper(localName = "GetPackagePickupAvailabilityXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupAvailabilityXMLResponse")
    @WebResult(name = "PackagePickupAvailabilityResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupAvailabilityResponse getPackagePickupAvailabilityXML(
        @WebParam(name = "PackagePickupAvailabilityRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String packagePickupAvailabilityRequestXML
    );

    @WebMethod(operationName = "GetNotificationSettingXML", action = "www.envmgr.com/LabelService/GetNotificationSettingXML")
    @RequestWrapper(localName = "GetNotificationSettingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetNotificationSettingXML")
    @ResponseWrapper(localName = "GetNotificationSettingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetNotificationSettingXMLResponse")
    @WebResult(name = "GetNotificationSettingListResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetNotificationSettingResult getNotificationSettingXML(
        @WebParam(name = "GetNotificationSettingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String getNotificationSettingRequestXML
    );

    @WebMethod(operationName = "GetPackagePickupXML", action = "www.envmgr.com/LabelService/GetPackagePickupXML")
    @RequestWrapper(localName = "GetPackagePickupXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupXML")
    @ResponseWrapper(localName = "GetPackagePickupXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupXMLResponse")
    @WebResult(name = "PackagePickupResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupResponse getPackagePickupXML(
        @WebParam(name = "PackagePickupRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String packagePickupRequestXML
    );

    @WebMethod(operationName = "ValidateAddressXML", action = "www.envmgr.com/LabelService/ValidateAddressXML")
    @RequestWrapper(localName = "ValidateAddressXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ValidateAddressXML")
    @ResponseWrapper(localName = "ValidateAddressXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ValidateAddressXMLResponse")
    @WebResult(name = "ValidateAddressResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ValidateAddressInfoResponse validateAddressXML(
        @WebParam(name = "ValidateAddressRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String validateAddressRequestXML
    );

    @WebMethod(operationName = "CreateBranding", action = "www.envmgr.com/LabelService/CreateBranding")
    @RequestWrapper(localName = "CreateBranding", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateBranding")
    @ResponseWrapper(localName = "CreateBrandingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateBrandingResponse")
    @WebResult(name = "GetBrandingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.CreateBrandingResult createBranding(
        @WebParam(name = "CreateBrandingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.CreateBrandingRequest createBrandingRequest
    );

    @WebMethod(operationName = "ResetSuspendedAccountXML", action = "www.envmgr.com/LabelService/ResetSuspendedAccountXML")
    @RequestWrapper(localName = "ResetSuspendedAccountXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ResetSuspendedAccountXML")
    @ResponseWrapper(localName = "ResetSuspendedAccountXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ResetSuspendedAccountXMLResponse")
    @WebResult(name = "ResetSuspendedAccountRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ResetSuspendedAccountRequestResponse resetSuspendedAccountXML(
        @WebParam(name = "ResetSuspendedAccountRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String resetSuspendedAccountRequestXML
    );

    @WebMethod(operationName = "ChangePassPhraseXML", action = "www.envmgr.com/LabelService/ChangePassPhraseXML")
    @RequestWrapper(localName = "ChangePassPhraseXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ChangePassPhraseXML")
    @ResponseWrapper(localName = "ChangePassPhraseXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.ChangePassPhraseXMLResponse")
    @WebResult(name = "ChangePassPhraseRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ChangePassPhraseRequestResponse changePassPhraseXML(
        @WebParam(name = "ChangePassPhraseRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String changePassPhraseRequestXML
    );

    @WebMethod(operationName = "CalculatePostageRates", action = "www.envmgr.com/LabelService/CalculatePostageRates")
    @RequestWrapper(localName = "CalculatePostageRates", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRates")
    @ResponseWrapper(localName = "CalculatePostageRatesResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRatesResponse")
    @WebResult(name = "PostageRatesResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PostageRatesResponse calculatePostageRates(
        @WebParam(name = "PostageRatesRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PostageRatesRequest postageRatesRequest
    );

    @WebMethod(operationName = "GetSCAN", action = "www.envmgr.com/LabelService/GetSCAN")
    @RequestWrapper(localName = "GetSCAN", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetSCAN")
    @ResponseWrapper(localName = "GetSCANResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetSCANResponse")
    @WebResult(name = "GetSCANResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.SCANResponse getSCAN(
        @WebParam(name = "GetSCANRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.SCANRequest getSCANRequest
    );

    @WebMethod(operationName = "GetPackagePickup", action = "www.envmgr.com/LabelService/GetPackagePickup")
    @RequestWrapper(localName = "GetPackagePickup", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickup")
    @ResponseWrapper(localName = "GetPackagePickupResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupResponse")
    @WebResult(name = "PackagePickupResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupResponse getPackagePickup(
        @WebParam(name = "PackagePickupRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PackagePickupRequest packagePickupRequest
    );

    @WebMethod(operationName = "GetPostageLabelXML", action = "www.envmgr.com/LabelService/GetPostageLabelXML")
    @RequestWrapper(localName = "GetPostageLabelXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageLabelXML")
    @ResponseWrapper(localName = "GetPostageLabelXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageLabelXMLResponse")
    @WebResult(name = "LabelRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.LabelRequestResponse getPostageLabelXML(
        @WebParam(name = "LabelRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String labelRequestXML
    );

    @WebMethod(operationName = "DeleteBranding", action = "www.envmgr.com/LabelService/DeleteBranding")
    @RequestWrapper(localName = "DeleteBranding", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteBranding")
    @ResponseWrapper(localName = "DeleteBrandingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteBrandingResponse")
    @WebResult(name = "DeleteBrandingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DeleteBrandingResult deleteBranding(
        @WebParam(name = "DeleteBrandingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.DeleteBrandingRequest deleteBrandingRequest
    );

    @WebMethod(operationName = "GetPostageRateTable", action = "www.envmgr.com/LabelService/GetPostageRateTable")
    @RequestWrapper(localName = "GetPostageRateTable", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageRateTable")
    @ResponseWrapper(localName = "GetPostageRateTableResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageRateTableResponse")
    @WebResult(name = "PostageRateResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PostageRateTableResponse getPostageRateTable(
        @WebParam(name = "PostageRateRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PostageRateRequest postageRateRequest
    );

    @WebMethod(operationName = "UpdatePaymentInformationXML", action = "www.envmgr.com/LabelService/UpdatePaymentInformationXML")
    @RequestWrapper(localName = "UpdatePaymentInformationXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdatePaymentInformationXML")
    @ResponseWrapper(localName = "UpdatePaymentInformationXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdatePaymentInformationXMLResponse")
    @WebResult(name = "UpdatePaymentInfoResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UpdatePaymentInfoResponse updatePaymentInformationXML(
        @WebParam(name = "UpdatePaymentInfoRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String updatePaymentInfoRequestXML
    );

    @WebMethod(operationName = "GetExtraServiceRatesXML", action = "www.envmgr.com/LabelService/GetExtraServiceRatesXML")
    @RequestWrapper(localName = "GetExtraServiceRatesXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetExtraServiceRatesXML")
    @ResponseWrapper(localName = "GetExtraServiceRatesXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetExtraServiceRatesXMLResponse")
    @WebResult(name = "GetExtraServiceRatesResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetExtraServiceRateResponse getExtraServiceRatesXML(
        @WebParam(name = "GetExtraServiceRatesRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String getExtraServiceRatesRequestXML
    );

    @WebMethod(operationName = "CreateDhlgmManifestXML", action = "www.envmgr.com/LabelService/CreateDhlgmManifestXML")
    @RequestWrapper(localName = "CreateDhlgmManifestXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateDhlgmManifestXML")
    @ResponseWrapper(localName = "CreateDhlgmManifestXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CreateDhlgmManifestXMLResponse")
    @WebResult(name = "CreateDhlgmManifestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DhlgmManifestResponse createDhlgmManifestXML(
        @WebParam(name = "CreateDhlgmManifestRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String createDhlgmManifestRequestXML
    );

    @WebMethod(operationName = "CalculatePostageRatesXML", action = "www.envmgr.com/LabelService/CalculatePostageRatesXML")
    @RequestWrapper(localName = "CalculatePostageRatesXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRatesXML")
    @ResponseWrapper(localName = "CalculatePostageRatesXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRatesXMLResponse")
    @WebResult(name = "PostageRatesResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PostageRatesResponse calculatePostageRatesXML(
        @WebParam(name = "PostageRatesRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String postageRatesRequestXML
    );

    @WebMethod(operationName = "GetUserSignUpXML", action = "www.envmgr.com/LabelService/GetUserSignUpXML")
    @RequestWrapper(localName = "GetUserSignUpXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUserSignUpXML")
    @ResponseWrapper(localName = "GetUserSignUpXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUserSignUpXMLResponse")
    @WebResult(name = "UserSignUpResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UserSignUpResponse getUserSignUpXML(
        @WebParam(name = "UserSignUpRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String userSignUpRequestXML
    );

    @WebMethod(operationName = "SetAccountFeatureOptIn", action = "www.envmgr.com/LabelService/SetAccountFeatureOptIn")
    @RequestWrapper(localName = "SetAccountFeatureOptIn", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.SetAccountFeatureOptIn")
    @ResponseWrapper(localName = "SetAccountFeatureOptInResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.SetAccountFeatureOptInResponse")
    @WebResult(name = "SetAccountFeatureOptInResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.SetAccountFeatureOptInResult setAccountFeatureOptIn(
        @WebParam(name = "SetAccountFeatureOptInRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.SetAccountFeatureOptInRequest setAccountFeatureOptInRequest
    );

    @WebMethod(operationName = "SetAccountFeatureOptInXML", action = "www.envmgr.com/LabelService/SetAccountFeatureOptInXML")
    @RequestWrapper(localName = "SetAccountFeatureOptInXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.SetAccountFeatureOptInXML")
    @ResponseWrapper(localName = "SetAccountFeatureOptInXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.SetAccountFeatureOptInXMLResponse")
    @WebResult(name = "SetAccountFeatureOptInResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.SetAccountFeatureOptInResult setAccountFeatureOptInXML(
        @WebParam(name = "SetAccountFeatureOptInRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String setAccountFeatureOptInRequestXML
    );

    @WebMethod(operationName = "GetRefund", action = "www.envmgr.com/LabelService/GetRefund")
    @RequestWrapper(localName = "GetRefund", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRefund")
    @ResponseWrapper(localName = "GetRefundResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRefundResponse")
    @WebResult(name = "RefundResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.RefundResponse getRefund(
        @WebParam(name = "RefundRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.RefundRequest refundRequest
    );

    @WebMethod(operationName = "GetUserSignUp", action = "www.envmgr.com/LabelService/GetUserSignUp")
    @RequestWrapper(localName = "GetUserSignUp", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUserSignUp")
    @ResponseWrapper(localName = "GetUserSignUpResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUserSignUpResponse")
    @WebResult(name = "UserSignUpResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UserSignUpResponse getUserSignUp(
        @WebParam(name = "UserSignUpRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.UserSignUpRequest userSignUpRequest
    );

    @WebMethod(operationName = "GetVersionXML", action = "www.envmgr.com/LabelService/GetVersionXML")
    @RequestWrapper(localName = "GetVersionXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetVersionXML")
    @ResponseWrapper(localName = "GetVersionXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetVersionXMLResponse")
    @WebResult(name = "GetVersionResults", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetVersionResults getVersionXML();

    @WebMethod(operationName = "CalculatePostageRate", action = "www.envmgr.com/LabelService/CalculatePostageRate")
    @RequestWrapper(localName = "CalculatePostageRate", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRate")
    @ResponseWrapper(localName = "CalculatePostageRateResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculatePostageRateResponse")
    @WebResult(name = "PostageRateResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PostageRateResponse calculatePostageRate(
        @WebParam(name = "PostageRateRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PostageRateRequest postageRateRequest
    );

    @WebMethod(operationName = "BuyPostage", action = "www.envmgr.com/LabelService/BuyPostage")
    @RequestWrapper(localName = "BuyPostage", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.BuyPostage")
    @ResponseWrapper(localName = "BuyPostageResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.BuyPostageResponse")
    @WebResult(name = "RecreditRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.RecreditRequestResponse buyPostage(
        @WebParam(name = "RecreditRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.RecreditRequest recreditRequest
    );

    @WebMethod(operationName = "GetBranding", action = "www.envmgr.com/LabelService/GetBranding")
    @RequestWrapper(localName = "GetBranding", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetBranding")
    @ResponseWrapper(localName = "GetBrandingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetBrandingResponse")
    @WebResult(name = "GetBrandingListResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetBrandingResult getBranding(
        @WebParam(name = "GetBrandingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.GetBrandingRequest getBrandingRequest
    );

    @WebMethod(operationName = "GetPicNumber", action = "www.envmgr.com/LabelService/GetPicNumber")
    @RequestWrapper(localName = "GetPicNumber", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPicNumber")
    @ResponseWrapper(localName = "GetPicNumberResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPicNumberResponse")
    @WebResult(name = "LabelNumberResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.LabelNumberResponse getPicNumber(
        @WebParam(name = "PicNumberRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PicNumberRequest picNumberRequest
    );

    @WebMethod(operationName = "GetPackagePickupListXML", action = "www.envmgr.com/LabelService/GetPackagePickupListXML")
    @RequestWrapper(localName = "GetPackagePickupListXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupListXML")
    @ResponseWrapper(localName = "GetPackagePickupListXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupListXMLResponse")
    @WebResult(name = "PackagePickupListResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupListResponse getPackagePickupListXML(
        @WebParam(name = "PackagePickupListRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String packagePickupListRequestXML
    );

    @WebMethod(operationName = "GetChallengeQuestionXML", action = "www.envmgr.com/LabelService/GetChallengeQuestionXML")
    @RequestWrapper(localName = "GetChallengeQuestionXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetChallengeQuestionXML")
    @ResponseWrapper(localName = "GetChallengeQuestionXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetChallengeQuestionXMLResponse")
    @WebResult(name = "ChallengeQuestionResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.ChallengeQuestionResponse getChallengeQuestionXML(
        @WebParam(name = "ChallengeQuestionRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String challengeQuestionRequestXML
    );

    @WebMethod(operationName = "GetPackagePickupChange", action = "www.envmgr.com/LabelService/GetPackagePickupChange")
    @RequestWrapper(localName = "GetPackagePickupChange", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupChange")
    @ResponseWrapper(localName = "GetPackagePickupChangeResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupChangeResponse")
    @WebResult(name = "PackagePickupChangeResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupChangeResponse getPackagePickupChange(
        @WebParam(name = "PackagePickupChangeRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PackagePickupChangeRequest packagePickupChangeRequest
    );

    @WebMethod(operationName = "UpdateNotificationSettingXML", action = "www.envmgr.com/LabelService/UpdateNotificationSettingXML")
    @RequestWrapper(localName = "UpdateNotificationSettingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateNotificationSettingXML")
    @ResponseWrapper(localName = "UpdateNotificationSettingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateNotificationSettingXMLResponse")
    @WebResult(name = "UpdateNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UpdateNotificationSettingResult updateNotificationSettingXML(
        @WebParam(name = "UpdateNotificationSettingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String updateNotificationSettingRequestXML
    );

    @WebMethod(operationName = "StatusRequestXML", action = "www.envmgr.com/LabelService/StatusRequestXML")
    @RequestWrapper(localName = "StatusRequestXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.StatusRequestXML")
    @ResponseWrapper(localName = "StatusRequestXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.StatusRequestXMLResponse")
    @WebResult(name = "PackageStatusResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackageStatusResponse statusRequestXML(
        @WebParam(name = "PackageStatusRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String packageStatusRequestXML
    );

    @WebMethod(operationName = "GetNotificationSetting", action = "www.envmgr.com/LabelService/GetNotificationSetting")
    @RequestWrapper(localName = "GetNotificationSetting", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetNotificationSetting")
    @ResponseWrapper(localName = "GetNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetNotificationSettingResponse")
    @WebResult(name = "GetNotificationSettingListResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetNotificationSettingResult getNotificationSetting(
        @WebParam(name = "GetNotificationSettingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.GetNotificationSettingRequest getNotificationSettingRequest
    );

    @WebMethod(operationName = "AddCarrier", action = "www.envmgr.com/LabelService/AddCarrier")
    @RequestWrapper(localName = "AddCarrier", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.AddCarrier")
    @ResponseWrapper(localName = "AddCarrierResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.AddCarrierResponse")
    @WebResult(name = "AddCarrierResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.AddCarrierResponseComplex addCarrier(
        @WebParam(name = "AddCarrierRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.AddCarrierRequest addCarrierRequest
    );

    @WebMethod(operationName = "CalculateDdpRateXML", action = "www.envmgr.com/LabelService/CalculateDdpRateXML")
    @RequestWrapper(localName = "CalculateDdpRateXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculateDdpRateXML")
    @ResponseWrapper(localName = "CalculateDdpRateXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.CalculateDdpRateXMLResponse")
    @WebResult(name = "DdpRateResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DdpRateResponse calculateDdpRateXML(
        @WebParam(name = "DdpRateRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String ddpRateRequestXML
    );

    @WebMethod(operationName = "GetPackagePickupAvailability", action = "www.envmgr.com/LabelService/GetPackagePickupAvailability")
    @RequestWrapper(localName = "GetPackagePickupAvailability", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupAvailability")
    @ResponseWrapper(localName = "GetPackagePickupAvailabilityResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupAvailabilityResponse")
    @WebResult(name = "PackagePickupAvailabilityResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupAvailabilityResponse getPackagePickupAvailability(
        @WebParam(name = "PackagePickupAvailabilityRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PackagePickupAvailabilityRequest packagePickupAvailabilityRequest
    );

    @WebMethod(operationName = "GetTransactionsListingXML", action = "www.envmgr.com/LabelService/GetTransactionsListingXML")
    @RequestWrapper(localName = "GetTransactionsListingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetTransactionsListingXML")
    @ResponseWrapper(localName = "GetTransactionsListingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetTransactionsListingXMLResponse")
    @WebResult(name = "TransactionsListingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.TransactionsListingResponse getTransactionsListingXML(
        @WebParam(name = "GetTransactionsListingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String getTransactionsListingRequestXML
    );

    @WebMethod(operationName = "GetPackagePickupChangeXML", action = "www.envmgr.com/LabelService/GetPackagePickupChangeXML")
    @RequestWrapper(localName = "GetPackagePickupChangeXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupChangeXML")
    @ResponseWrapper(localName = "GetPackagePickupChangeXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupChangeXMLResponse")
    @WebResult(name = "PackagePickupChangeResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupChangeResponse getPackagePickupChangeXML(
        @WebParam(name = "PackagePickupChangeRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String packagePickupChangeRequestXML
    );

    @WebMethod(operationName = "UpdateBranding", action = "www.envmgr.com/LabelService/UpdateBranding")
    @RequestWrapper(localName = "UpdateBranding", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateBranding")
    @ResponseWrapper(localName = "UpdateBrandingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateBrandingResponse")
    @WebResult(name = "UpdateBrandingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UpdateBrandingResult updateBranding(
        @WebParam(name = "UpdateBrandingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.UpdateBrandingRequest updateBrandingRequest
    );

    @WebMethod(operationName = "GetPostageLabel", action = "www.envmgr.com/LabelService/GetPostageLabel")
    @RequestWrapper(localName = "GetPostageLabel", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageLabel")
    @ResponseWrapper(localName = "GetPostageLabelResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPostageLabelResponse")
    @WebResult(name = "LabelRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.LabelRequestResponse getPostageLabel(
        @WebParam(name = "LabelRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.LabelRequest labelRequest
    );

    @WebMethod(operationName = "GetAccountStatus", action = "www.envmgr.com/LabelService/GetAccountStatus")
    @RequestWrapper(localName = "GetAccountStatus", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetAccountStatus")
    @ResponseWrapper(localName = "GetAccountStatusResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetAccountStatusResponse")
    @WebResult(name = "AccountStatusResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.AccountStatusResponse getAccountStatus(
        @WebParam(name = "AccountStatusRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.AccountStatusRequest accountStatusRequest
    );

    @WebMethod(operationName = "VoideVSLabel", action = "www.envmgr.com/LabelService/VoideVSLabel")
    @RequestWrapper(localName = "VoideVSLabel", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.VoideVSLabel")
    @ResponseWrapper(localName = "VoideVSLabelResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.VoideVSLabelResponse")
    @WebResult(name = "VoidLabelResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.VoidLabelResponse voideVSLabel(
        @WebParam(name = "VoidLabelRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.VoidLabelRequest voidLabelRequest
    );

    @WebMethod(operationName = "GetPackagePickupCancel", action = "www.envmgr.com/LabelService/GetPackagePickupCancel")
    @RequestWrapper(localName = "GetPackagePickupCancel", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupCancel")
    @ResponseWrapper(localName = "GetPackagePickupCancelResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetPackagePickupCancelResponse")
    @WebResult(name = "PackagePickupCancelResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.PackagePickupCancelResponse getPackagePickupCancel(
        @WebParam(name = "PackagePickupCancelRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.PackagePickupCancelRequest packagePickupCancelRequest
    );

    @WebMethod(operationName = "GetRetailAccounts", action = "www.envmgr.com/LabelService/GetRetailAccounts")
    @RequestWrapper(localName = "GetRetailAccounts", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRetailAccounts")
    @ResponseWrapper(localName = "GetRetailAccountsResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetRetailAccountsResponse")
    @WebResult(name = "RetailAccountsResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.RetailAccountsResponse getRetailAccounts(
        @WebParam(name = "RetailAccountsRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.RetailAccountsRequest retailAccountsRequest
    );

    @WebMethod(operationName = "DeleteBrandingXML", action = "www.envmgr.com/LabelService/DeleteBrandingXML")
    @RequestWrapper(localName = "DeleteBrandingXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteBrandingXML")
    @ResponseWrapper(localName = "DeleteBrandingXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.DeleteBrandingXMLResponse")
    @WebResult(name = "DeleteBrandingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.DeleteBrandingResult deleteBrandingXML(
        @WebParam(name = "DeleteBrandingRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String deleteBrandingRequestXML
    );

    @WebMethod(operationName = "GetUrl", action = "www.envmgr.com/LabelService/GetUrl")
    @RequestWrapper(localName = "GetUrl", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUrl")
    @ResponseWrapper(localName = "GetUrlResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.GetUrlResponse")
    @WebResult(name = "GetUrlResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.GetUrlResult getUrl(
        @WebParam(name = "GetUrlRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.GetUrlRequest getUrlRequest
    );

    @WebMethod(operationName = "UpdateNotificationSetting", action = "www.envmgr.com/LabelService/UpdateNotificationSetting")
    @RequestWrapper(localName = "UpdateNotificationSetting", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateNotificationSetting")
    @ResponseWrapper(localName = "UpdateNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.UpdateNotificationSettingResponse")
    @WebResult(name = "UpdateNotificationSettingResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.UpdateNotificationSettingResult updateNotificationSetting(
        @WebParam(name = "UpdateNotificationSettingRequest", targetNamespace = "www.envmgr.com/LabelService")
        com.envmgr.labelservice.UpdateNotificationSettingRequest updateNotificationSettingRequest
    );

    @WebMethod(operationName = "BuyPostageXML", action = "www.envmgr.com/LabelService/BuyPostageXML")
    @RequestWrapper(localName = "BuyPostageXML", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.BuyPostageXML")
    @ResponseWrapper(localName = "BuyPostageXMLResponse", targetNamespace = "www.envmgr.com/LabelService", className = "com.envmgr.labelservice.BuyPostageXMLResponse")
    @WebResult(name = "RecreditRequestResponse", targetNamespace = "www.envmgr.com/LabelService")
    public com.envmgr.labelservice.RecreditRequestResponse buyPostageXML(
        @WebParam(name = "RecreditRequestXML", targetNamespace = "www.envmgr.com/LabelService")
        java.lang.String recreditRequestXML
    );
}
