
package com.envmgr.labelservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-10-29T10:49:43.767-03:00
 * Generated source version: 3.2.7
 *
 */
public final class EwsLabelServiceSoap_EwsLabelServiceSoap_Client {

    private static final QName SERVICE_NAME = new QName("www.envmgr.com/LabelService", "EwsLabelService");

    private EwsLabelServiceSoap_EwsLabelServiceSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EwsLabelService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        EwsLabelService ss = new EwsLabelService(wsdlURL, SERVICE_NAME);
        EwsLabelServiceSoap port = ss.getEwsLabelServiceSoap();

        {
        System.out.println("Invoking calculateDdpRate...");
        com.envmgr.labelservice.DdpRateRequest _calculateDdpRate_ddpRateRequest = null;
        com.envmgr.labelservice.DdpRateResponse _calculateDdpRate__return = port.calculateDdpRate(_calculateDdpRate_ddpRateRequest);
        System.out.println("calculateDdpRate.result=" + _calculateDdpRate__return);


        }
        {
        System.out.println("Invoking getExtraServiceRates...");
        com.envmgr.labelservice.GetExtraServiceRatesRequest _getExtraServiceRates_getExtraServiceRatesRequest = null;
        com.envmgr.labelservice.GetExtraServiceRateResponse _getExtraServiceRates__return = port.getExtraServiceRates(_getExtraServiceRates_getExtraServiceRatesRequest);
        System.out.println("getExtraServiceRates.result=" + _getExtraServiceRates__return);


        }
        {
        System.out.println("Invoking statusRequest...");
        com.envmgr.labelservice.PackageStatusRequest _statusRequest_packageStatusRequest = null;
        com.envmgr.labelservice.PackageStatusResponse _statusRequest__return = port.statusRequest(_statusRequest_packageStatusRequest);
        System.out.println("statusRequest.result=" + _statusRequest__return);


        }
        {
        System.out.println("Invoking getPicNumberXml...");
        java.lang.String _getPicNumberXml_picNumberRequestXml = "";
        com.envmgr.labelservice.LabelNumberResponse _getPicNumberXml__return = port.getPicNumberXml(_getPicNumberXml_picNumberRequestXml);
        System.out.println("getPicNumberXml.result=" + _getPicNumberXml__return);


        }
        {
        System.out.println("Invoking getRefundXML...");
        java.lang.String _getRefundXML_refundRequestXML = "";
        com.envmgr.labelservice.RefundResponse _getRefundXML__return = port.getRefundXML(_getRefundXML_refundRequestXML);
        System.out.println("getRefundXML.result=" + _getRefundXML__return);


        }
        {
        System.out.println("Invoking closeAccount...");
        com.envmgr.labelservice.CloseAccountRequest _closeAccount_closeAccountRequest = null;
        com.envmgr.labelservice.SetPendingCloseAccountResponse _closeAccount__return = port.closeAccount(_closeAccount_closeAccountRequest);
        System.out.println("closeAccount.result=" + _closeAccount__return);


        }
        {
        System.out.println("Invoking updatePaymentInformation...");
        com.envmgr.labelservice.UpdatePaymentInfoRequest _updatePaymentInformation_updatePaymentInfoRequest = null;
        com.envmgr.labelservice.UpdatePaymentInfoResponse _updatePaymentInformation__return = port.updatePaymentInformation(_updatePaymentInformation_updatePaymentInfoRequest);
        System.out.println("updatePaymentInformation.result=" + _updatePaymentInformation__return);


        }
        {
        System.out.println("Invoking changePassPhrase...");
        com.envmgr.labelservice.ChangePassPhraseRequest _changePassPhrase_changePassPhraseRequest = null;
        com.envmgr.labelservice.ChangePassPhraseRequestResponse _changePassPhrase__return = port.changePassPhrase(_changePassPhrase_changePassPhraseRequest);
        System.out.println("changePassPhrase.result=" + _changePassPhrase__return);


        }
        {
        System.out.println("Invoking getPostageRateTableXML...");
        java.lang.String _getPostageRateTableXML_postageRateRequestXML = "";
        com.envmgr.labelservice.PostageRateTableResponse _getPostageRateTableXML__return = port.getPostageRateTableXML(_getPostageRateTableXML_postageRateRequestXML);
        System.out.println("getPostageRateTableXML.result=" + _getPostageRateTableXML__return);


        }
        {
        System.out.println("Invoking resetSuspendedAccount...");
        com.envmgr.labelservice.ResetSuspendedAccountRequest _resetSuspendedAccount_resetSuspendedAccountRequest = null;
        com.envmgr.labelservice.ResetSuspendedAccountRequestResponse _resetSuspendedAccount__return = port.resetSuspendedAccount(_resetSuspendedAccount_resetSuspendedAccountRequest);
        System.out.println("resetSuspendedAccount.result=" + _resetSuspendedAccount__return);


        }
        {
        System.out.println("Invoking calculatePostageRateXML...");
        java.lang.String _calculatePostageRateXML_postageRateRequestXML = "";
        com.envmgr.labelservice.PostageRateResponse _calculatePostageRateXML__return = port.calculatePostageRateXML(_calculatePostageRateXML_postageRateRequestXML);
        System.out.println("calculatePostageRateXML.result=" + _calculatePostageRateXML__return);


        }
        {
        System.out.println("Invoking getRetailAccountsXML...");
        java.lang.String _getRetailAccountsXML_retailAccountsRequestXML = "";
        com.envmgr.labelservice.RetailAccountsResponse _getRetailAccountsXML__return = port.getRetailAccountsXML(_getRetailAccountsXML_retailAccountsRequestXML);
        System.out.println("getRetailAccountsXML.result=" + _getRetailAccountsXML__return);


        }
        {
        System.out.println("Invoking getVersion...");
        com.envmgr.labelservice.GetVersionResults _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking validateAddress...");
        com.envmgr.labelservice.ValidateAddressInfoRequest _validateAddress_validateAddressRequest = null;
        com.envmgr.labelservice.ValidateAddressInfoResponse _validateAddress__return = port.validateAddress(_validateAddress_validateAddressRequest);
        System.out.println("validateAddress.result=" + _validateAddress__return);


        }
        {
        System.out.println("Invoking createDhlgmManifest...");
        com.envmgr.labelservice.CreateDhlgmManifestRequest _createDhlgmManifest_createDhlgmManifestRequest = null;
        com.envmgr.labelservice.DhlgmManifestResponse _createDhlgmManifest__return = port.createDhlgmManifest(_createDhlgmManifest_createDhlgmManifestRequest);
        System.out.println("createDhlgmManifest.result=" + _createDhlgmManifest__return);


        }
        {
        System.out.println("Invoking getTransactionsListing...");
        com.envmgr.labelservice.GetTransactionsListingRequest _getTransactionsListing_getTransactionsListingRequest = null;
        com.envmgr.labelservice.TransactionsListingResponse _getTransactionsListing__return = port.getTransactionsListing(_getTransactionsListing_getTransactionsListingRequest);
        System.out.println("getTransactionsListing.result=" + _getTransactionsListing__return);


        }
        {
        System.out.println("Invoking closeAccountXML...");
        java.lang.String _closeAccountXML_closeAccountRequestXML = "";
        com.envmgr.labelservice.SetPendingCloseAccountResponse _closeAccountXML__return = port.closeAccountXML(_closeAccountXML_closeAccountRequestXML);
        System.out.println("closeAccountXML.result=" + _closeAccountXML__return);


        }
        {
        System.out.println("Invoking getAccountStatusXML...");
        java.lang.String _getAccountStatusXML_accountStatusRequestXML = "";
        com.envmgr.labelservice.AccountStatusResponse _getAccountStatusXML__return = port.getAccountStatusXML(_getAccountStatusXML_accountStatusRequestXML);
        System.out.println("getAccountStatusXML.result=" + _getAccountStatusXML__return);


        }
        {
        System.out.println("Invoking voideVSLabelXML...");
        java.lang.String _voideVSLabelXML_voidLabelRequestXML = "";
        com.envmgr.labelservice.VoidLabelResponse _voideVSLabelXML__return = port.voideVSLabelXML(_voideVSLabelXML_voidLabelRequestXML);
        System.out.println("voideVSLabelXML.result=" + _voideVSLabelXML__return);


        }
        {
        System.out.println("Invoking getPackagePickupCancelXML...");
        java.lang.String _getPackagePickupCancelXML_packagePickupCancelRequestXML = "";
        com.envmgr.labelservice.PackagePickupCancelResponse _getPackagePickupCancelXML__return = port.getPackagePickupCancelXML(_getPackagePickupCancelXML_packagePickupCancelRequestXML);
        System.out.println("getPackagePickupCancelXML.result=" + _getPackagePickupCancelXML__return);


        }
        {
        System.out.println("Invoking getChallengeQuestion...");
        com.envmgr.labelservice.ChallengeQuestionRequest _getChallengeQuestion_challengeQuestionRequest = null;
        com.envmgr.labelservice.ChallengeQuestionResponse _getChallengeQuestion__return = port.getChallengeQuestion(_getChallengeQuestion_challengeQuestionRequest);
        System.out.println("getChallengeQuestion.result=" + _getChallengeQuestion__return);


        }
        {
        System.out.println("Invoking getPackagePickupAvailabilityXML...");
        java.lang.String _getPackagePickupAvailabilityXML_packagePickupAvailabilityRequestXML = "";
        com.envmgr.labelservice.PackagePickupAvailabilityResponse _getPackagePickupAvailabilityXML__return = port.getPackagePickupAvailabilityXML(_getPackagePickupAvailabilityXML_packagePickupAvailabilityRequestXML);
        System.out.println("getPackagePickupAvailabilityXML.result=" + _getPackagePickupAvailabilityXML__return);


        }
        {
        System.out.println("Invoking getSCANXML...");
        java.lang.String _getSCANXML_getSCANRequestXML = "";
        com.envmgr.labelservice.SCANResponse _getSCANXML__return = port.getSCANXML(_getSCANXML_getSCANRequestXML);
        System.out.println("getSCANXML.result=" + _getSCANXML__return);


        }
        {
        System.out.println("Invoking getPackagePickupXML...");
        java.lang.String _getPackagePickupXML_packagePickupRequestXML = "";
        com.envmgr.labelservice.PackagePickupResponse _getPackagePickupXML__return = port.getPackagePickupXML(_getPackagePickupXML_packagePickupRequestXML);
        System.out.println("getPackagePickupXML.result=" + _getPackagePickupXML__return);


        }
        {
        System.out.println("Invoking validateAddressXML...");
        java.lang.String _validateAddressXML_validateAddressRequestXML = "";
        com.envmgr.labelservice.ValidateAddressInfoResponse _validateAddressXML__return = port.validateAddressXML(_validateAddressXML_validateAddressRequestXML);
        System.out.println("validateAddressXML.result=" + _validateAddressXML__return);


        }
        {
        System.out.println("Invoking resetSuspendedAccountXML...");
        java.lang.String _resetSuspendedAccountXML_resetSuspendedAccountRequestXML = "";
        com.envmgr.labelservice.ResetSuspendedAccountRequestResponse _resetSuspendedAccountXML__return = port.resetSuspendedAccountXML(_resetSuspendedAccountXML_resetSuspendedAccountRequestXML);
        System.out.println("resetSuspendedAccountXML.result=" + _resetSuspendedAccountXML__return);


        }
        {
        System.out.println("Invoking changePassPhraseXML...");
        java.lang.String _changePassPhraseXML_changePassPhraseRequestXML = "";
        com.envmgr.labelservice.ChangePassPhraseRequestResponse _changePassPhraseXML__return = port.changePassPhraseXML(_changePassPhraseXML_changePassPhraseRequestXML);
        System.out.println("changePassPhraseXML.result=" + _changePassPhraseXML__return);


        }
        {
        System.out.println("Invoking calculatePostageRates...");
        com.envmgr.labelservice.PostageRatesRequest _calculatePostageRates_postageRatesRequest = null;
        com.envmgr.labelservice.PostageRatesResponse _calculatePostageRates__return = port.calculatePostageRates(_calculatePostageRates_postageRatesRequest);
        System.out.println("calculatePostageRates.result=" + _calculatePostageRates__return);


        }
        {
        System.out.println("Invoking getSCAN...");
        com.envmgr.labelservice.SCANRequest _getSCAN_getSCANRequest = null;
        com.envmgr.labelservice.SCANResponse _getSCAN__return = port.getSCAN(_getSCAN_getSCANRequest);
        System.out.println("getSCAN.result=" + _getSCAN__return);


        }
        {
        System.out.println("Invoking getPackagePickup...");
        com.envmgr.labelservice.PackagePickupRequest _getPackagePickup_packagePickupRequest = null;
        com.envmgr.labelservice.PackagePickupResponse _getPackagePickup__return = port.getPackagePickup(_getPackagePickup_packagePickupRequest);
        System.out.println("getPackagePickup.result=" + _getPackagePickup__return);


        }
        {
        System.out.println("Invoking getPostageLabelXML...");
        java.lang.String _getPostageLabelXML_labelRequestXML = "";
        com.envmgr.labelservice.LabelRequestResponse _getPostageLabelXML__return = port.getPostageLabelXML(_getPostageLabelXML_labelRequestXML);
        System.out.println("getPostageLabelXML.result=" + _getPostageLabelXML__return);


        }
        {
        System.out.println("Invoking updatePaymentInformationXML...");
        java.lang.String _updatePaymentInformationXML_updatePaymentInfoRequestXML = "";
        com.envmgr.labelservice.UpdatePaymentInfoResponse _updatePaymentInformationXML__return = port.updatePaymentInformationXML(_updatePaymentInformationXML_updatePaymentInfoRequestXML);
        System.out.println("updatePaymentInformationXML.result=" + _updatePaymentInformationXML__return);


        }
        {
        System.out.println("Invoking getPostageRateTable...");
        com.envmgr.labelservice.PostageRateRequest _getPostageRateTable_postageRateRequest = null;
        com.envmgr.labelservice.PostageRateTableResponse _getPostageRateTable__return = port.getPostageRateTable(_getPostageRateTable_postageRateRequest);
        System.out.println("getPostageRateTable.result=" + _getPostageRateTable__return);


        }
        {
        System.out.println("Invoking getExtraServiceRatesXML...");
        java.lang.String _getExtraServiceRatesXML_getExtraServiceRatesRequestXML = "";
        com.envmgr.labelservice.GetExtraServiceRateResponse _getExtraServiceRatesXML__return = port.getExtraServiceRatesXML(_getExtraServiceRatesXML_getExtraServiceRatesRequestXML);
        System.out.println("getExtraServiceRatesXML.result=" + _getExtraServiceRatesXML__return);


        }
        {
        System.out.println("Invoking createDhlgmManifestXML...");
        java.lang.String _createDhlgmManifestXML_createDhlgmManifestRequestXML = "";
        com.envmgr.labelservice.DhlgmManifestResponse _createDhlgmManifestXML__return = port.createDhlgmManifestXML(_createDhlgmManifestXML_createDhlgmManifestRequestXML);
        System.out.println("createDhlgmManifestXML.result=" + _createDhlgmManifestXML__return);


        }
        {
        System.out.println("Invoking calculatePostageRatesXML...");
        java.lang.String _calculatePostageRatesXML_postageRatesRequestXML = "";
        com.envmgr.labelservice.PostageRatesResponse _calculatePostageRatesXML__return = port.calculatePostageRatesXML(_calculatePostageRatesXML_postageRatesRequestXML);
        System.out.println("calculatePostageRatesXML.result=" + _calculatePostageRatesXML__return);


        }
        {
        System.out.println("Invoking setAccountFeatureOptInXML...");
        java.lang.String _setAccountFeatureOptInXML_setAccountFeatureOptInRequestXML = "";
        com.envmgr.labelservice.SetAccountFeatureOptInResult _setAccountFeatureOptInXML__return = port.setAccountFeatureOptInXML(_setAccountFeatureOptInXML_setAccountFeatureOptInRequestXML);
        System.out.println("setAccountFeatureOptInXML.result=" + _setAccountFeatureOptInXML__return);


        }
        {
        System.out.println("Invoking setAccountFeatureOptIn...");
        com.envmgr.labelservice.SetAccountFeatureOptInRequest _setAccountFeatureOptIn_setAccountFeatureOptInRequest = null;
        com.envmgr.labelservice.SetAccountFeatureOptInResult _setAccountFeatureOptIn__return = port.setAccountFeatureOptIn(_setAccountFeatureOptIn_setAccountFeatureOptInRequest);
        System.out.println("setAccountFeatureOptIn.result=" + _setAccountFeatureOptIn__return);


        }
        {
        System.out.println("Invoking getUserSignUpXML...");
        java.lang.String _getUserSignUpXML_userSignUpRequestXML = "";
        com.envmgr.labelservice.UserSignUpResponse _getUserSignUpXML__return = port.getUserSignUpXML(_getUserSignUpXML_userSignUpRequestXML);
        System.out.println("getUserSignUpXML.result=" + _getUserSignUpXML__return);


        }
        {
        System.out.println("Invoking getRefund...");
        com.envmgr.labelservice.RefundRequest _getRefund_refundRequest = null;
        com.envmgr.labelservice.RefundResponse _getRefund__return = port.getRefund(_getRefund_refundRequest);
        System.out.println("getRefund.result=" + _getRefund__return);


        }
        {
        System.out.println("Invoking getUserSignUp...");
        com.envmgr.labelservice.UserSignUpRequest _getUserSignUp_userSignUpRequest = null;
        com.envmgr.labelservice.UserSignUpResponse _getUserSignUp__return = port.getUserSignUp(_getUserSignUp_userSignUpRequest);
        System.out.println("getUserSignUp.result=" + _getUserSignUp__return);


        }
        {
        System.out.println("Invoking getVersionXML...");
        com.envmgr.labelservice.GetVersionResults _getVersionXML__return = port.getVersionXML();
        System.out.println("getVersionXML.result=" + _getVersionXML__return);


        }
        {
        System.out.println("Invoking calculatePostageRate...");
        com.envmgr.labelservice.PostageRateRequest _calculatePostageRate_postageRateRequest = null;
        com.envmgr.labelservice.PostageRateResponse _calculatePostageRate__return = port.calculatePostageRate(_calculatePostageRate_postageRateRequest);
        System.out.println("calculatePostageRate.result=" + _calculatePostageRate__return);


        }
        {
        System.out.println("Invoking buyPostage...");
        com.envmgr.labelservice.RecreditRequest _buyPostage_recreditRequest = null;
        com.envmgr.labelservice.RecreditRequestResponse _buyPostage__return = port.buyPostage(_buyPostage_recreditRequest);
        System.out.println("buyPostage.result=" + _buyPostage__return);


        }
        {
        System.out.println("Invoking getPicNumber...");
        com.envmgr.labelservice.PicNumberRequest _getPicNumber_picNumberRequest = null;
        com.envmgr.labelservice.LabelNumberResponse _getPicNumber__return = port.getPicNumber(_getPicNumber_picNumberRequest);
        System.out.println("getPicNumber.result=" + _getPicNumber__return);


        }
        {
        System.out.println("Invoking getChallengeQuestionXML...");
        java.lang.String _getChallengeQuestionXML_challengeQuestionRequestXML = "";
        com.envmgr.labelservice.ChallengeQuestionResponse _getChallengeQuestionXML__return = port.getChallengeQuestionXML(_getChallengeQuestionXML_challengeQuestionRequestXML);
        System.out.println("getChallengeQuestionXML.result=" + _getChallengeQuestionXML__return);


        }
        {
        System.out.println("Invoking getPackagePickupChange...");
        com.envmgr.labelservice.PackagePickupChangeRequest _getPackagePickupChange_packagePickupChangeRequest = null;
        com.envmgr.labelservice.PackagePickupChangeResponse _getPackagePickupChange__return = port.getPackagePickupChange(_getPackagePickupChange_packagePickupChangeRequest);
        System.out.println("getPackagePickupChange.result=" + _getPackagePickupChange__return);


        }
        {
        System.out.println("Invoking statusRequestXML...");
        java.lang.String _statusRequestXML_packageStatusRequestXML = "";
        com.envmgr.labelservice.PackageStatusResponse _statusRequestXML__return = port.statusRequestXML(_statusRequestXML_packageStatusRequestXML);
        System.out.println("statusRequestXML.result=" + _statusRequestXML__return);


        }
        {
        System.out.println("Invoking calculateDdpRateXML...");
        java.lang.String _calculateDdpRateXML_ddpRateRequestXML = "";
        com.envmgr.labelservice.DdpRateResponse _calculateDdpRateXML__return = port.calculateDdpRateXML(_calculateDdpRateXML_ddpRateRequestXML);
        System.out.println("calculateDdpRateXML.result=" + _calculateDdpRateXML__return);


        }
        {
        System.out.println("Invoking getPackagePickupAvailability...");
        com.envmgr.labelservice.PackagePickupAvailabilityRequest _getPackagePickupAvailability_packagePickupAvailabilityRequest = null;
        com.envmgr.labelservice.PackagePickupAvailabilityResponse _getPackagePickupAvailability__return = port.getPackagePickupAvailability(_getPackagePickupAvailability_packagePickupAvailabilityRequest);
        System.out.println("getPackagePickupAvailability.result=" + _getPackagePickupAvailability__return);


        }
        {
        System.out.println("Invoking handleDHLeCManifest...");
        com.envmgr.labelservice.DHLeCManifestRequest _handleDHLeCManifest_dhLeCManifestRequest = null;
        com.envmgr.labelservice.DHLeCManifestResponse _handleDHLeCManifest__return = port.handleDHLeCManifest(_handleDHLeCManifest_dhLeCManifestRequest);
        System.out.println("handleDHLeCManifest.result=" + _handleDHLeCManifest__return);


        }
        {
        System.out.println("Invoking getTransactionsListingXML...");
        java.lang.String _getTransactionsListingXML_getTransactionsListingRequestXML = "";
        com.envmgr.labelservice.TransactionsListingResponse _getTransactionsListingXML__return = port.getTransactionsListingXML(_getTransactionsListingXML_getTransactionsListingRequestXML);
        System.out.println("getTransactionsListingXML.result=" + _getTransactionsListingXML__return);


        }
        {
        System.out.println("Invoking getPackagePickupChangeXML...");
        java.lang.String _getPackagePickupChangeXML_packagePickupChangeRequestXML = "";
        com.envmgr.labelservice.PackagePickupChangeResponse _getPackagePickupChangeXML__return = port.getPackagePickupChangeXML(_getPackagePickupChangeXML_packagePickupChangeRequestXML);
        System.out.println("getPackagePickupChangeXML.result=" + _getPackagePickupChangeXML__return);


        }
        {
        System.out.println("Invoking getAccountStatus...");
        com.envmgr.labelservice.AccountStatusRequest _getAccountStatus_accountStatusRequest = null;
        com.envmgr.labelservice.AccountStatusResponse _getAccountStatus__return = port.getAccountStatus(_getAccountStatus_accountStatusRequest);
        System.out.println("getAccountStatus.result=" + _getAccountStatus__return);


        }
        {
        System.out.println("Invoking getPostageLabel...");
        com.envmgr.labelservice.LabelRequest _getPostageLabel_labelRequest = null;
        com.envmgr.labelservice.LabelRequestResponse _getPostageLabel__return = port.getPostageLabel(_getPostageLabel_labelRequest);
        System.out.println("getPostageLabel.result=" + _getPostageLabel__return);


        }
        {
        System.out.println("Invoking voideVSLabel...");
        com.envmgr.labelservice.VoidLabelRequest _voideVSLabel_voidLabelRequest = null;
        com.envmgr.labelservice.VoidLabelResponse _voideVSLabel__return = port.voideVSLabel(_voideVSLabel_voidLabelRequest);
        System.out.println("voideVSLabel.result=" + _voideVSLabel__return);


        }
        {
        System.out.println("Invoking getPackagePickupCancel...");
        com.envmgr.labelservice.PackagePickupCancelRequest _getPackagePickupCancel_packagePickupCancelRequest = null;
        com.envmgr.labelservice.PackagePickupCancelResponse _getPackagePickupCancel__return = port.getPackagePickupCancel(_getPackagePickupCancel_packagePickupCancelRequest);
        System.out.println("getPackagePickupCancel.result=" + _getPackagePickupCancel__return);


        }
        {
        System.out.println("Invoking handleDHLeCManifestXML...");
        java.lang.String _handleDHLeCManifestXML_dhLeCManifestRequestXML = "";
        com.envmgr.labelservice.DHLeCManifestResponse _handleDHLeCManifestXML__return = port.handleDHLeCManifestXML(_handleDHLeCManifestXML_dhLeCManifestRequestXML);
        System.out.println("handleDHLeCManifestXML.result=" + _handleDHLeCManifestXML__return);


        }
        {
        System.out.println("Invoking getRetailAccounts...");
        com.envmgr.labelservice.RetailAccountsRequest _getRetailAccounts_retailAccountsRequest = null;
        com.envmgr.labelservice.RetailAccountsResponse _getRetailAccounts__return = port.getRetailAccounts(_getRetailAccounts_retailAccountsRequest);
        System.out.println("getRetailAccounts.result=" + _getRetailAccounts__return);


        }
        {
        System.out.println("Invoking buyPostageXML...");
        java.lang.String _buyPostageXML_recreditRequestXML = "";
        com.envmgr.labelservice.RecreditRequestResponse _buyPostageXML__return = port.buyPostageXML(_buyPostageXML_recreditRequestXML);
        System.out.println("buyPostageXML.result=" + _buyPostageXML__return);


        }

        System.exit(0);
    }

}
